FROM node:22-alpine

WORKDIR /app

COPY apps/web/package.json ./
RUN npm install

COPY apps/web ./

ARG API_URL=http://api:8000
ENV API_URL=$API_URL \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
