from enum import StrEnum


class IngestionMethod(StrEnum):
    RSS = "RSS"
    API = "API"
    HTML = "HTML"
    UNKNOWN = "UNKNOWN"


class SourceItemStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class EventStatus(StrEnum):
    DETECTED = "DETECTED"
    PROCESSING = "PROCESSING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    PUBLISHED = "PUBLISHED"
    UPDATING = "UPDATING"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class EventSourceRelation(StrEnum):
    INITIAL = "INITIAL"
    CONFIRMING = "CONFIRMING"
    ADDITIONAL = "ADDITIONAL"
    CONTRADICTING = "CONTRADICTING"
    CORRECTING = "CORRECTING"
    REPEATING = "REPEATING"


class ClaimStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    SINGLE_SOURCE = "SINGLE_SOURCE"
    CONFLICTING = "CONFLICTING"
    UNCERTAIN = "UNCERTAIN"
    DISPROVEN = "DISPROVEN"
    OUTDATED = "OUTDATED"


class ClaimImportance(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class EvidenceType(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    QUALIFIES = "QUALIFIES"
    MENTIONS = "MENTIONS"


class EditorialLabel(StrEnum):
    CHECKED = "CHECKED"
    DISCREPANCY = "DISCREPANCY"
    DISPUTED = "DISPUTED"
    FALSE_CLAIM = "FALSE_CLAIM"


class EntityType(StrEnum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    COMPANY = "COMPANY"
    GOVERNMENT = "GOVERNMENT"
    PLACE = "PLACE"
    OTHER = "OTHER"


class LocationPrecision(StrEnum):
    INTERSECTION = "INTERSECTION"
    ADDRESS = "ADDRESS"
    NEIGHBORHOOD = "NEIGHBORHOOD"
    LOCALITY = "LOCALITY"
    PROVINCE = "PROVINCE"
    COUNTRY = "COUNTRY"
    UNKNOWN = "UNKNOWN"


class EventUpdateType(StrEnum):
    EVENT_CREATED = "EVENT_CREATED"
    NEW_INFORMATION = "NEW_INFORMATION"
    OFFICIAL_CONFIRMATION = "OFFICIAL_CONFIRMATION"
    CORRECTION = "CORRECTION"
    CONFLICT_FOUND = "CONFLICT_FOUND"
    CONFLICT_RESOLVED = "CONFLICT_RESOLVED"
    ARTICLE_UPDATED = "ARTICLE_UPDATED"


class ArticleStatus(StrEnum):
    DRAFT = "DRAFT"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    PUBLISHED = "PUBLISHED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class PipelineStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    RETRY = "RETRY"
    FAILED = "FAILED"


class CaseStatus(StrEnum):
    RECEIVED = "RECEIVED"
    REVIEWING = "REVIEWING"
    RESOLVED = "RESOLVED"


class CaseOutcome(StrEnum):
    CORRECTED = "CORRECTED"
    UPDATED = "UPDATED"
    RESPONSE_INCORPORATED = "RESPONSE_INCORPORATED"
    NO_CHANGE = "NO_CHANGE"
    INQUIRY_ANSWERED = "INQUIRY_ANSWERED"


class CaseReason(StrEnum):
    INCORRECT_FACT = "INCORRECT_FACT"
    MISSING_INFO = "MISSING_INFO"
    SOURCE_MISREAD = "SOURCE_MISREAD"
    CONTRIBUTE_INFO = "CONTRIBUTE_INFO"
    INVOLVED_RESPONSE = "INVOLVED_RESPONSE"
    WHY_WRITTEN = "WHY_WRITTEN"
    WHY_PUBLISHED = "WHY_PUBLISHED"
    OTHER = "OTHER"


class CaseActionType(StrEnum):
    CREATED = "CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    NOTE_ADDED = "NOTE_ADDED"
    RESOLVED = "RESOLVED"
    CORRECTION_LINKED = "CORRECTION_LINKED"


class CaseActor(StrEnum):
    READER = "READER"
    ADMIN = "ADMIN"


class CorrectionKind(StrEnum):
    CORRECTION = "CORRECTION"
    UPDATE = "UPDATE"


class EditorialRevisionKind(StrEnum):
    MINOR = "MINOR"
    UPDATE = "UPDATE"
    CORRECTION = "CORRECTION"
